function [txPoints, rxPoints, scattererPoints] = generate_setup(antenna_spacing, ...
    num_antennas, scatterer_spacing, scatterer_grid_size, grid_height)
%GENERATE_SETUP Generates the TX, RX and scatterer points

% Get scatterer grid positions 
scattererPoints = xy_grid(scatterer_spacing, ...
    scatterer_spacing, ...
    scatterer_grid_size, ...
    scatterer_grid_size, ...
    grid_height);

% Get TX array positions 
tx1 = xy_grid(0, ...
    antenna_spacing, ...
    1, ...
    num_antennas, ...
    0, ...
    'xCoord', -(num_antennas + 1) / 2 * antenna_spacing);

tx2 = xy_grid(0, ...
    antenna_spacing, ...
    1, ...
    num_antennas, ...
    0, ...
    'xCoord', (num_antennas + 1) / 2 * antenna_spacing);

txPoints = [tx1; tx2];

% Get RX array positions 
rx1 = xy_grid(antenna_spacing, ...
    0, ...
    num_antennas, ...
    1, ...
    0, ...
    'yCoord', -(num_antennas + 1) / 2 * antenna_spacing);

rx2 = xy_grid(antenna_spacing, ...
    0, ...
    num_antennas, ...
    1, ...
    0, ...
    'yCoord', (num_antennas + 1) / 2 * antenna_spacing);

rxPoints = [rx1; rx2];

end

